### PR TITLE
Ensure all exceptions are retried.

### LINKED ISSUE #70: Catch all unexpected exceptions
In the `connect` method, if the heartbeat fails for any reason other than a `PhoenixException`, the `PhoenixSocket` will stop attempting reconnects, and manually calling `connect` does nothing. This causes our app to end up in a "broken" state, where the app is disconnected & the user cannot reconnect.

As a consumer of the library, manually calling `connect` does nothing, since the `_ws` variable is not reset to `null`, which means the library simply returns `this`, but does not reconnect, nor does it throw any kind of exception we could respond to. Furthermore, as the caller, you cannot know that an error has occurred, because nothing is emitted to the `errorStream`.

In addition, unexpected exceptions are not caught in the `_sendHeartbeat` and propagated to the consumer (the `connect` method). Therefore, when something goes wrong in this method, there is no way for the connect method respond appropriately.

This is related to #68. The library should fundamentally ensure that *all* exceptions are handled. Otherwise, we end up in "Black hole" scenarios, where something goes wrong, but we cannot react to it in any way by attempting a reconnect, resetting the socket entirely, or even just sending the information to an error reporting service like Crashlytics or Sentry so we can evaluate the exception and fix the underlying issue if possible.

I'll post a PR to address these issues shortly!

### PR DESCRIPTION
**Pull request by brian-superlist**
Fixes #70. 

This PR ensures that if non-`PhoenixException` exceptions are raised when attempting to send the heartbeat, the socket will attempt to reconnect. This should fix one case where the socket is left in a "broken" state, where it stops scheduling reconnects and cannot be connected to manually.

As part of this PR, I also renamed any tests that were hitting a real backend as an `_integration_test`, since it is a true integration test against a backend, not a unit test that can rely on mocks. I can also go the other way, calling the new socket test a `socket_unit_test.dart` if that's preferred. I don't feel strongly, but I think it's important not to mix the two tests, as the integration tests are run on CI but harder to run locally.

### CODE REVIEW

File: lib/src/socket.dart [hunk 1]
```diff
@@ -443,8 +449,11 @@ class PhoenixSocket {
         err,
         stacktrace,
       );
-      return false;
-    } on WebSocketChannelException catch (err, stacktrace) {
+
+      // Rethrow instead of returning false to ensure the original
+      // PhoenixException is propagated to the call site.
+      rethrow;
```
Comment (brian-superlist) [inline lib/src/socket.dart:455]: Question: should we `_triggerChannelExceptions` on `PhoenixException` as well? It seems odd only to trigger on other types of exceptions 🤔

Comment (miguelcmedeiros) [reply lib/src/socket.dart:455]: When `_sendHeartbeat()` is called from `connect()`, if it returns `false` (which is the case when `sendMessage(heartbeat)` throws `PhoenixException`), then it throws `PhoenixException` and catches it right after so that it can schedule a reconnect.

My assumption is that in this case we assume that's something wrong with the socket and try to reconnect, whereas the case of `sendMessage(heartbeat)` throwing `WebSocketChannelException`, then it's a problem with the channel, which calls `_triggerChannelExceptions()` in order to attempt a channel rejoin.

Should we then call `_triggerChannelExceptions()` for exceptions other than `WebSocketChannelException`?

Comment (brian-superlist) [reply lib/src/socket.dart:455]: Ah fair point. Let me adjust that.

Comment (brian-superlist) [reply lib/src/socket.dart:461]: I've reverted the code so we only call `_triggerChannelExceptions` on `WebSocketChannelException`. In all other cases, we now `rethrow` to propagate the underlying error to the caller so it can reconnect.

**Comment by matehat** [comment]
Thanks!
